export const techStack = [
    { name: "React", icon: "/icons/react-icon.svg.png" },
    { name: "TypeScript", icon: "/icons/typescript-icon.svg.png" },
    { name: "Tailwind", icon: "/icons/tailwind-CSS-icon.svg.png" },
    { name: "Framer Motion", icon: "/icons/framer-motion-icon.svg" },
    { name: "HTML5", icon: "/icons/HTML5-icon.svg.png" },
    { name: "CSS3", icon: "/icons/CSS3-logo.svg" },
    { name: "Styled components", icon: "/icons/styled-components.svg" },
    { name: "Ant design", icon: "/icons/ant-design.svg" },
    { name: "Bootstrap", icon: "/icons/bootstrap-logo.svg.png" },
    { name: "javaScript", icon: "/icons/javaScript-icon.svg.png" },
    { name: "GraphQL", icon: "/icons/graphQL-icon.svg.png" },
    { name: "RESTful AP", icon: "/icons/api-restFull-icon.svg" },
    { name: "Git", icon: "/icons/git-icon.svg.png" },
    { name: "Github", icon: "/icons/github-icon.svg" },
    { name: "Docker", icon: "/icons/docker.svg" },
    { name: "Jest", icon: "/icons/jest-icon.svg" },
    { name: "Postman", icon: "/icons/postman-icon.svg" },
    { name: "VS Code", icon: "/icons/visual-studio-icon.svg.png" },
]